package dao;

public  enum Pairs {
	BTC_USD, BTC_EUR, BTC_RUB, BTC_UAH, 
	DASH_BTC, DASH_USD, ETH_BTC, ETH_USD, 
	DOGE_BTC, LTC_BTC, ETH_RUB, ETH_EUR, 
	LTC_RUB, DASH_RUB, ETH_LTC, USD_RUB, 
	WAVES_BTC
}
